game/apps/characters/urls.py
from django.conf.urls import patterns, url
from .views import CharacterDetail, CharacterCreate, CreateMatch, CharacterImage

urlpatterns = [
    url(r'^(?P<pk>\d+)$', CharacterDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/create/$', CreateMatch.as_view(), name='create'),
    url(r'^create/$', CharacterCreate.as_view(), name='create_char'),
    url(r'^(?P<pk>\d+)/image/$', CharacterImage, name="CharacterImage"),
]

game/apps/matches/urls.py
from django.conf.urls import patterns, url
from .views import CreateMatch, MatchDetail, AttackForm, MatchList

urlpatterns = [
    url(r'^(?P<pk>\d+)/attack/$', AttackForm.as_view(), name='attack'),
    url(r'^$', MatchList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', MatchDetail.as_view(), name='detail'),
]

game/apps/messaging/urls.py
from django.conf.urls import patterns, url
from .views import MessageList

urlpatterns = [
    url(r'^$', MessageList.as_view(), name="MessageList"),
]

game/urls.py
from django.conf.urls import include, url
from .views import Homepage
from game.apps.characters.views import CharacterLeaderboard
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()
from rest_framework import routers
from game.apps.items import views

router = routers.DefaultRouter()
router.register(r'items', views.ItemAcquiredViewSet)



urlpatterns = [
	url(r'^api/', include(router.urls)),
    url(r'^match/', include('game.apps.matches.urls',  namespace="match")),
    url(r'^character/', include('game.apps.characters.urls', namespace="character")),
    url(r'^messages/', include('game.apps.messaging.urls', namespace="messaging")),
    url(r'^', include('game.apps.userprofiles.urls', namespace="userprofile")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', Homepage.as_view(), name='homepage'),
    url(r'^login/$', auth_views.login),
    url(r'^logout/$', auth_views.logout),
    url(r'^leaderboard/$', CharacterLeaderboard.as_view(), name="leaderbaord"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/apps/matches/models.py
from django.db import models
from game.apps.enemies.models import Enemy
from game.apps.characters.models import Character
from game.apps.spells.models import Spell

class Match(models.Model):

    character = models.ForeignKey(
        Character,
        )

    enemy = models.ForeignKey(
        Enemy,
        )

    character_health = models.PositiveIntegerField(
        "Current Character Health",
        blank=True,
        )

    enemy_health = models.PositiveIntegerField(
        "Current Enemy Health",
        blank=True,
        )

    resource = models.PositiveIntegerField(
        default=1,
        )

    finished = models.BooleanField(
        default=False,
        )

    class Meta:
        verbose_name_plural = "Matches"

    def __unicode__(self):
        return self.character.name

    @models.permalink
    def get_absolute_url(self):
            return ("match:detail", (), {
                "pk": self.pk
            })


class Attack(models.Model):

    match = models.ForeignKey(
        Match
        )

    spell = models.ForeignKey(
        Spell
        )

    enemy_return_spell = models.ForeignKey(
        Spell,
        null=True,
        related_name='reliation'
        )

    damage_dealt = models.PositiveIntegerField(
        null=True,
        )

    damage_taken = models.PositiveIntegerField(
        null=True,
        )

    time = models.TimeField(
        null=True,
        )

game/apps/characters/forms.py
from django import forms
from .models import Character
from game.apps.matches.models import Match

class CharacterCreate(forms.ModelForm):
    error_css_class = "error"

    class Meta:
        model = Character
        exclude = ['user', 'health', 'xp']


class CreateMatch(forms.ModelForm):

    class Meta:
        model = Match
        exclude = ['character_health', 'enemy_health', 'resource', 'character']

game/apps/matches/forms.py
from django import forms
from .models import Match, Attack


class CreateMatch(forms.ModelForm):

    class Meta:
        model = Match
        exclude = ['character_health', 'enemy_health', 'resource']


class AttackForm(forms.ModelForm):

    class Meta:
        model = Attack
        exclude = ['time', 'enemy_return_spell', 'match', 'damage_dealt', 'damage_taken']

game/apps/userprofiles/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name", "email"]

game/apps/characters/views.py
from django.views.generic import DetailView, CreateView, ListView
from .models import Character, Class
from .forms import CharacterCreate, CreateMatch
from game.apps.matches.models import Match, Enemy
from django.views.generic.edit import ModelFormMixin
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from game.apps.matches.helpers import calculate_player_health, calculate_boss_health
from game.apps.spells.models import SpellAcquired
from game.apps.items.models import ItemAcquired, Position
from PIL import Image, ImageDraw, ImageOps
from random import randint
from django.http import HttpResponse


class CharacterLeaderboard(ListView):
    model = Character

    def get_context_data(self, **kwargs):
        context = super(CharacterLeaderboard, self).get_context_data(**kwargs)
        context['character_list'] = Character.objects.all().order_by('-xp')[:100]
        return context


class CharacterDetail(DetailView):
    model = Character


    def get_context_data(self, **kwargs):
        context = super(CharacterDetail, self).get_context_data(**kwargs)
        
        equipped_items =  ItemAcquired.objects.filter(character=self.object.pk, equipped_to__isnull=False)
        spells_acquired = SpellAcquired.objects.filter(character=self.object.pk)
        postions = Position.objects.all()
        context['spells'] = spells_acquired

        for i in postions:
            context[i.name.replace (" ", "_").lower()] = i

        for i in equipped_items:
            context["item_" + i.equipped_to.name.replace (" ", "_").lower()] = i.item.image.url
            context[i.equipped_to.name.replace (" ", "_").lower() + "_id"] = i.id


        return context


class CreateMatch(CreateView):
    model = Match
    form_class = CreateMatch

    def get_context_data(self, **kwargs):
        context = super(CreateMatch, self).get_context_data(**kwargs)
        character = get_object_or_404(
            Character,
            pk=self.kwargs.get('pk'),
            user=self.request.user
        )
        context['character'] = character

        context['enemys'] = Enemy.objects.all()
        return context

    def form_valid(self, form):
        Form = form.save(commit=False)
        boss = form.cleaned_data['enemy']
        Form.enemy_health = calculate_boss_health(boss)
        Form.resource = 1
        character = Character.objects.get(pk=self.kwargs['pk'])
        Form.character = character
        Form.character_health = calculate_player_health(character)
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class CharacterCreate(CreateView):
    model = Character
    form_class = CharacterCreate

    def form_valid(self, form):
        charactercreate = form.save(commit=False)
        charactercreate.user = self.request.user
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CharacterCreate, self).get_context_data(**kwargs)
        context['types'] = Class.objects.all()
        return context

    def get_success_url(self):
        return reverse('character:detail', kwargs={'pk': self.object.pk})


def CharacterImage(request, pk):

    character =Character.objects.get(id=pk)
    media = "game/media/items/"
    background = Image.open("game/static/img/character-type/" + character.for_class.name + ".png")
    background = ImageOps.expand(background,border=80)

    equipped_items = ItemAcquired.objects.filter(character=pk, equipped_to__isnull=False)


    item_mapping = {
        'Head': (200, 27),
        'Left Hand': (55, 27),
    }

    hat = Image.open(media + "hat_nxY7RAW.png")
    background.paste(hat, (200, 27), hat)

    sword = Image.open(media + "sword-mounted_l9Rz3r8.png")
    background.paste(sword, (55, 27), sword)

    for i in equipped_items:
        item_image = Image.open("game" + i.item.image.url)
        background.paste(item_image, item_mapping[str(i.equipped_to)], item_image)

    response = HttpResponse(content_type="image/png")
    background.save(response, "PNG")


    return response

game/apps/items/views.py
from rest_framework import viewsets
from .serializers import ItemAcquiredSerializer, ItemSerializer
from .models import Item, ItemAcquired
from django.http import HttpResponse
from rest_framework.permissions import IsAuthenticated


class ItemAcquiredViewSet(viewsets.ModelViewSet):
    serializer_class = ItemAcquiredSerializer
    queryset = ItemAcquired.objects.all()
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        user = self.request.user
        return ItemAcquired.objects.filter(character__user=user)

game/apps/matches/views.py
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import ModelFormMixin
from .models import Match, Attack
from game.apps.characters.models import Character
from game.apps.enemies.models import Enemy
from .forms import CreateMatch, AttackForm
from game.apps.spells.models import Spell
from django.utils.timezone import now
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from .helpers import calculate_player_damage, calculate_boss_damage, calculate_player_health,  calculate_boss_health, calculate_xp


class CreateMatch(CreateView):
    model = Match
    form_class = CreateMatch

    def get_context_data(self, **kwargs):
        context = super(CreateMatch, self).get_context_data(**kwargs)
        context['characters'] = Character.objects.filter(user=self.request.user)
        context['enemys'] = Enemy.objects.all()
        return context

    def form_valid(self, form):
        Form = form.save(commit=False)
        boss = form.cleaned_data['enemy']
        Form.enemy_health = calculate_boss_health(boss)
        Form.resource = 1
        character = form.cleaned_data['character']
        Form.character_health = calculate_player_health(character)
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class MatchDetail(DetailView):
    model = Match

    def get_context_data(self, **kwargs):
        context = super(MatchDetail, self).get_context_data(**kwargs)

        context['spells'] = Spell.objects.filter(
            for_class=self.object.character.for_class,
            level_required__lte=context['match'].character.level_data()['current_level'],
        )

        match = get_object_or_404(
            Match,
            pk=self.kwargs.get('pk'),
            character__user=self.request.user,
        )

        if self.object.enemy_health == 0:
            context['condition'] = "win"
        else:
            if self.object.character_health == 0:
                context['condition'] = "loose"
            else:
                pass

        context['match'] = match

        cooldown = False

        for spell in context['spells']:
            attack_history_list = Attack.objects.filter(match=122).order_by('-time')[:spell.turn_cooldown]
            print attack_history_list
            for attack_history in attack_history_list:
                if attack_history.spell == attack_history_list:
                    cooldown = True
                    print cooldown
                    print attack_history.spell
                    context['cooldown'] = cooldown
                    break
                else:
                    cooldown = False
                    print cooldown
                    print attack_history.spell
                    context['cooldown'] = cooldown
        return context


class MatchList(ListView):
    model = Match


class AttackForm(CreateView):
    model = Attack
    form_class = AttackForm

    def get_context_data(self, **kwargs):
        context = super(AttackForm, self).get_context_data(**kwargs)
        match = get_object_or_404(
            Match,
            pk=self.kwargs.get('pk'),
            character__user=self.request.user
        )
        context['match'] = match
        return context

    def form_valid(self, form):
        spell = form.cleaned_data['spell']
        attackform = form.save(commit=False)
        match = Match.objects.get(id=self.kwargs['pk'])
        boss_spell = Spell.objects.filter(level_required__lte=match.enemy.level).order_by('?')[0]
        character_level = match.character.level_data()['current_level']
        attackform.enemy_return_spell = boss_spell
        character = match
        attackform.selected_spell = spell
        cooldown = False
        attack_history_list = Attack.objects.filter(match=match).order_by('-time')[:spell.turn_cooldown]
        player_damage = calculate_player_damage(character, spell)
        boss_damage = calculate_boss_damage(boss_spell, match)

        for attack_history in attack_history_list:
            if attack_history.spell == spell:
                cooldown = True
                break
            else:
                cooldown = False

        if spell.level_required <= character_level and spell.for_class == match.character.for_class and cooldown == False:

            if match.finished is False:
                if match.enemy_health <= player_damage:
                    match.enemy_health = 0
                    match.character.xp += calculate_xp(match)
                    match.finished = True
                else:
                    if match.character_health <= boss_damage:
                        match.character_health = 0
                        match.finished = True
                    else:
                        match.enemy_health -= player_damage
                        match.character_health -= boss_damage

            else:
                return super(ModelFormMixin, self).form_valid(form)

            attackform.damage_dealt = player_damage
            attackform.damage_taken = boss_damage

            attackform.match = match
            attackform.time = now()
            match.save()
            match.character.save()
            self.object = attackform.save()

            return super(ModelFormMixin, self).form_valid(form)
        else:
            return super(ModelFormMixin, self).form_valid(form)

    def get_success_url(self):
        return reverse('match:detail', kwargs={'pk': self.kwargs['pk']})

game/apps/messaging/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Message


class MessageList(ListView):
	model = Message

game/apps/userprofiles/views.py
from django.views.generic import UpdateView, DetailView
from django.views.generic.edit import ModelFormMixin
from .forms import UserProfileForm
from .models import UserProfile
from django.contrib.auth.models import User
from game.apps.characters.models import Character
from game.apps.matches.models import Match, Attack
from game.apps.spells.models import SpellAcquired, Spell


class UserProfilePage(UpdateView):
    model = UserProfile
    success_url = '/settings/'
    form_class = UserProfileForm
    template_name = 'userprofile/UserProfile_form.html'

    def form_valid(self, form):
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(UserProfilePage, self).get_context_data(**kwargs)
        characters = Character.objects.filter(user=self.object.pk)
        context['characters'] = characters

        wins = Match.objects.filter(character__in=characters, enemy_health=0).count()
        loses = Match.objects.filter(character__in=characters, character_health=0).count();

        total_damage_dealt = 0
        total_damage_taken = 0

        matches = Match.objects.filter(character__in=characters)
        for attack in Attack.objects.filter(match__in=matches):
            total_damage_dealt += attack.damage_dealt
            total_damage_taken += attack.damage_taken

        spell_used_list = {}
        for element in SpellAcquired.objects.filter(character__in=characters):
            spell_used_list[element.spell.name] = Attack.objects.filter(match__in=matches, spell=element.spell).count()

        most_used = max(spell_used_list, key=spell_used_list.get)
        most_used_spell = Spell.objects.get(name=most_used)

        context['wins'] = wins
        context['loses'] = loses
        context['percent_of_wins'] = str(round(float(wins - loses) / wins * 100, 1)) + "%";
        context['most_used_spell'] = most_used_spell
        context['total_damage_dealt'] = total_damage_dealt
        context['total_damage_taken'] = total_damage_taken
        return context

game/views.py
from django.views.generic import ListView
from game.apps.characters.models import Character

class Homepage(ListView):
    model = Character
    template_name = 'site/homepage.html'

    def get_context_data(self, **kwargs):
        context = super(Homepage, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            context['characters'] = Character.objects.filter(user=self.request.user)
        else:
            pass
        return context

game/templates/matches/attack_form.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="large-6 columns">
        <h1>Attack</h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Attack" class="button">
        </form>
    </div>
</div>
{% endblock content %}

game/templates/matches/match_detail.html
{% extends "base.html" %}
{% block content %}

{% if condition %}
{% if condition == "win" %}
<div class="wrap">
    <div class="cube">
        <div class="front"></div>
        <div class="back"></div>
        <div class="top"></div>
        <div class="bottom"></div>
        <div class="left"></div>
        <div class="right"></div>
    </div>
</div>

{% endif %}
{% if condition == "loose" %}
   <center> <h1>You lost!</h1></center>
{% endif %}
{% endif %}

<a href="#" onclick="EndTurn()" style="
    background: #19963C;
    color: #FFF;
    position: absolute;
    right: 0;
    top: 35%;
    padding: 20px 45px;
">End Turn</a>
<div id="cards">
<div class="card">
    <div class="face front">
        <img src="http://localhost:8000/media/spells/spell.png">
        <h4>Fireball</h4>
    </div>
    <div class="face back"></div>
</div>

<div class="card">
    <div class="face front">
        <img src="http://localhost:8000/media/spells/spell.png">
        <h4>Fireball</h4>
    </div>
    <div class="face back"></div>
</div>

<div class="card">
    <div class="face front">
        <img src="http://localhost:8000/media/spells/spell.png">
        <h4>Fireball</h4>
    </div>
    <div class="face back"></div>
</div>
</div>
<div class="bottompanel">
 <div class="large-2 columns">
    <img src="http://localhost:8000/character/1/image/" class="characterimg">
 </div>

  <div class="large-4 columns">
  
    <div class="xcontain">
        <a><img src="/static/img/castspell.png"></a>
        <a onclick="ChanceSpell()"><img src="/static/img/chance.png"></a>
        <a><img src="/static/img/cardpickup.png"></a>
    </div>



</div>
    <div class="large-3 columns">
        <div class="spellpreview">
        <img src="http://localhost:8000/media/spells/spell.png"><h4>Fireball</h4>
        </div>

        <ul class="spells">
        <li class="selected"><img src="http://localhost:8000/media/spells/spell.png"></li>
        <li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li><li></li></ul>
    </div>
    <div class="large-1 columns">
        <ul id="manor">
            <li></li><li></li><li></li><li></li>
        </ul>
    </div>

    <div class="large-2 columns">
        <div class="health">
            <img src="/static/img/heart.png">
            <h2><small>Health</small> {{ match.character_health }}</h2>
        </div>
    </div>
</div>
</div>

<!--
<div class="md-heading">
    <div class="row">
        <div class="large-12 columns">
            <div class="large-5 columns">
                <h1>{{ match.character }} <small>{{ match.character_health }}</small></h1>
                <small>Level {% with level_data=match.character.level_data %}{{ level_data.current_level }} {% endwith %}</small>
            </div>

            <div class="large-2 columns">
                <center>
                    <h1><small>vs</small></h1>
                </center>
            </div>
            <div class="large-5 columns">
                <h1>{{ match.enemy }} <small>{{ match.enemy_health }}</small></h1>
                <small>Level {{ match.enemy.level }} </small>
            </div>
            <div class="large-5 columns">
                
            </div>
            <div class="large-5 columns">
                
            </div>
        </div>
    </div>
</div>
<hr>
<div class="row">
    <div class="large-12 columns">
        <div class="match">
            This is where the game takes place!
            <div class="tooltip">edit me</div>
        <div class="panel historybox">
            <h3>History</h3>
            <hr>
            {% for attack in match.attack_set.all %}
            <li>Sent {{ attack.damage_dealt }}, Took {{ attack.damage_taken }}</li>
            {% endfor %}
        </div>


        </div>
    </div>
</div>
<div class="row">
    <div class="large-12 columns">
        <form action="/match/{{ match.id }}/attack/" method="post">
            {% csrf_token %}
            <ul class="spell_list">
                {% for spell in spells %}
                    <li>
                        <a data-tooltip aria-haspopup="true" class="has-tip" title="Damage: {{ spell.damage }}
                        Cooldown {{ spell.turn_cooldown }} {{ spell.cooldown }}">
                        <input type="radio" name="spell" value="{{ spell.id }}" id="{{ spell.name }}{{ spell.id }}">
                        <label for="{{ spell.name }}{{ spell.id }}" class="testlabel" required>{{ spell.name }}</label>
                        </a>
                    </li>
                {% endfor %}
                    <li>

                        <input type="radio" name="spell" value="{{ spell.id }}" id="{{ spell.name }}{{ spell.id }}" class="disabled"><label for="{{ spell.name }}{{ spell.id }}" class="testlabel disabled">Disabled Spell</label>
                    </li>
            </ul>
            <div class="large-12 columns left">
                <hr>
                <input type="submit" value="End Turn" class="button">
            </div>
        </form>
    </div>
    <div class="large-5 columns">

    </div>
-->
{% endblock content %}
{% block js %}
<script type="text/javascript">

var manor = 12;
UpdateManor(); 
function ChanceSpell() {
    var newmanor = manor - 4;
    if (newmanor >= 0){
        manor -= 4;
        PlaceCard();
    }
    else {
        alert("Sorry you don't have enough manor");
    }
    UpdateManor();
}

function UpdateManor() {
    var html = []
    for (var i = 0; i < manor; i++) { 
    html.push("<li></li>");
    }
    $('#manor').html(html) 
}

function PlaceCard() {

    var html = '<div class="card"><div class="face front"></div><div class="face back"></div></div>'
    $('#cards').append(html);
}

function EndTurn() {
    $('#cards div').addClass("front");
}

</script>
{% endblock %}

game/templates/matches/match_form.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="large-12 columns">
        <form action="" method="post">
            <ul class="map">
                {% csrf_token %}
                {% for enemy in enemys %}
                    <li>
                        <input type="radio" name="enemy" value="{{ enemy.id }}" id="{{ enemy.name }}{{ enemy.id }}">
                        <label for="{{ enemy.name }}{{ enemy.id }}" style="top: {{ enemy.top }}px; left: {{ enemy.left }}px" required>
                            {{ enemy.name }} ({{ enemy.level }})
                        </label>
                    </li>
                {% endfor %}
            </ul>
            <input type="submit" value="Start Match" class="button">
        </form>
    </div>
</div>
{% endblock content %}

game/templates/matches/match_list.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <h1>Matches</h1>
    <p>All of the matches, these will be filtered to only yours soon</p>
    {% for match in match_list  %}
        <a href="/match/{{ match.id }}">{{ match.character }}</a>
    {% endfor %}
</div>
{% endblock content %}