game/apps/characters/urls.py
from django.conf.urls import patterns, url
from .views import CharacterDetail, CharacterCreate, CreateMatch, CharacterImage

urlpatterns = [
    url(r'^(?P<pk>\d+)$', CharacterDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/create/$', CreateMatch.as_view(), name='create'),
    url(r'^create/$', CharacterCreate.as_view(), name='create_char'),
    url(r'^(?P<pk>\d+)/image/$', CharacterImage, name="CharacterImage"),
]

game/apps/matches/urls.py
from django.conf.urls import patterns, url
from .views import CreateMatch, MatchDetail, AttackForm, MatchList

urlpatterns = [
    url(r'^(?P<pk>\d+)/attack/$', AttackForm.as_view(), name='attack'),
    url(r'^$', MatchList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', MatchDetail.as_view(), name='detail'),
]

game/apps/messaging/urls.py
from django.conf.urls import patterns, url
from .views import MessageList

urlpatterns = [
    url(r'^$', MessageList.as_view(), name="MessageList"),
]

game/urls.py
from django.conf.urls import include, url
from .views import Homepage
from game.apps.characters.views import CharacterLeaderboard
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()
from rest_framework import routers
from game.apps.items import views

router = routers.DefaultRouter()
router.register(r'items', views.ItemAcquiredViewSet)



urlpatterns = [
	url(r'^api/', include(router.urls)),
    url(r'^match/', include('game.apps.matches.urls',  namespace="match")),
    url(r'^character/', include('game.apps.characters.urls', namespace="character")),
    url(r'^messages/', include('game.apps.messaging.urls', namespace="messaging")),
    url(r'^', include('game.apps.userprofiles.urls', namespace="userprofile")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', Homepage.as_view(), name='homepage'),
    url(r'^login/$', auth_views.login),
    url(r'^logout/$', auth_views.logout),
    url(r'^leaderboard/$', CharacterLeaderboard.as_view(), name="leaderbaord"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game/apps/items/models.py
from django.db import models
from game.apps.characters.models import Character, Class
from django.core.exceptions import ValidationError


class Group(models.Model):
    name = models.CharField(
        max_length=200,
        unique=True,
    )

    def __unicode__(self):
        return self.name


class Position(models.Model):

    name = models.CharField(
        max_length=200,
        unique=True,
        )

    def __unicode__(self):
        return self.name


class Item(models.Model):

    name = models.CharField(
        max_length=200,
        unique=True,
    )

    icon = models.ImageField(
        upload_to='icon',
        blank=True,
        null=True,
    )

    image = models.ImageField(
        upload_to='items',
        blank=True,
        null=True,
    )

    group = models.ForeignKey(
	    Group,
    )

    worth = models.DecimalField(
	    decimal_places=2,
        max_digits=100,
    )

    for_class = models.ForeignKey(
	    Class,
    )

    level_required = models.PositiveIntegerField(
    )

    damage = models.PositiveIntegerField(
        default=0,
        null=True,
    )

    healing = models.PositiveIntegerField(
        default=0,
        null=True,
    )

    armor = models.PositiveIntegerField(
        default=0,
        null=True,
    )

    position = models.ManyToManyField(
        'Position',
        default=None,
        )

    def __unicode__(self):
        return self.name


class ItemAcquired(models.Model):
    character = models.ForeignKey(
        Character
        )
    item = models.ForeignKey(
        Item,
    )

    equipped_to = models.ForeignKey(
        Position,
        null=True,
        blank=True,
        )

    class Meta:
        unique_together = (('item','equipped_to'),)


    def clean(self):
        #raise ValidationError("test")
        # Checks to see if item is the same class as the character
        try:
            Item.objects.get(id=self.item.id, for_class=self.character.for_class)
        except:
            raise ValidationError('Your character is the wrong class for this item.')

        
        if self.equipped_to:
            # Check if character is high enough level
            if not self.character.level_data()['current_level'] >= self.item.level_required:
                raise ValidationError('You are not a high enough level to equip this item.')

            # Checks to see if item can be equipped in place requested
            try:
                item = Item.objects.get(id=self.item.id, position=self.equipped_to.id)
            except:
                raise ValidationError('This item cannot be equipped here.')
        
            # Check to see if item is equipped somewhere else.
            if ItemAcquired.objects.filter(character=self.character, item=self.item,  equipped_to__isnull=False).exclude(pk=self.pk):
                raise ValidationError('This item is already equipped somewhere else.')

            # Check to see if another item is equipped in that place

            if ItemAcquired.objects.filter(character=self.character, equipped_to=self.equipped_to).exclude(pk=self.pk):
                raise ValidationError('Another item is equipped here.')

game/apps/matches/models.py
from django.db import models
from game.apps.enemies.models import Enemy
from game.apps.characters.models import Character
from game.apps.spells.models import Spell

class Match(models.Model):

    character = models.ForeignKey(
        Character,
        )

    enemy = models.ForeignKey(
        Enemy,
        )

    character_health = models.PositiveIntegerField(
        "Current Character Health",
        blank=True,
        )

    enemy_health = models.PositiveIntegerField(
        "Current Enemy Health",
        blank=True,
        )

    resource = models.PositiveIntegerField(
        default=1,
        )

    finished = models.BooleanField(
        default=False,
        )

    class Meta:
        verbose_name_plural = "Matches"

    def __unicode__(self):
        return self.character.name

    @models.permalink
    def get_absolute_url(self):
            return ("match:detail", (), {
                "pk": self.pk
            })


class Attack(models.Model):

    match = models.ForeignKey(
        Match
        )

    spell = models.ForeignKey(
        Spell
        )

    enemy_return_spell = models.ForeignKey(
        Spell,
        null=True,
        related_name='reliation'
        )

    damage_dealt = models.PositiveIntegerField(
        null=True,
        )

    damage_taken = models.PositiveIntegerField(
        null=True,
        )

    time = models.TimeField(
        null=True,
        )

game/apps/characters/views.py
from django.views.generic import DetailView, CreateView, ListView
from .models import Character, Class
from .forms import CharacterCreate, CreateMatch
from game.apps.matches.models import Match, Enemy
from django.views.generic.edit import ModelFormMixin
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from game.apps.matches.helpers import calculate_player_health, calculate_boss_health
from game.apps.spells.models import SpellAcquired
from game.apps.items.models import ItemAcquired, Position
from PIL import Image, ImageDraw, ImageOps
from random import randint
from django.http import HttpResponse


class CharacterLeaderboard(ListView):
    model = Character

    def get_context_data(self, **kwargs):
        context = super(CharacterLeaderboard, self).get_context_data(**kwargs)
        context['character_list'] = Character.objects.all().order_by('-xp')[:100]
        return context


class CharacterDetail(DetailView):
    model = Character


    def get_context_data(self, **kwargs):
        context = super(CharacterDetail, self).get_context_data(**kwargs)
        
        equipped_items =  ItemAcquired.objects.filter(character=self.object.pk, equipped_to__isnull=False)
        spells_acquired = SpellAcquired.objects.filter(character=self.object.pk)
        postions = Position.objects.all()
        context['spells'] = spells_acquired

        for i in postions:
            context[i.name.replace (" ", "_").lower()] = i

        for i in equipped_items:
            context["item_" + i.equipped_to.name.replace (" ", "_").lower()] = i.item.image.url
            context[i.equipped_to.name.replace (" ", "_").lower() + "_id"] = i.id


        return context


class CreateMatch(CreateView):
    model = Match
    form_class = CreateMatch

    def get_context_data(self, **kwargs):
        context = super(CreateMatch, self).get_context_data(**kwargs)
        character = get_object_or_404(
            Character,
            pk=self.kwargs.get('pk'),
            user=self.request.user
        )
        context['character'] = character

        context['enemys'] = Enemy.objects.all()
        return context

    def form_valid(self, form):
        Form = form.save(commit=False)
        boss = form.cleaned_data['enemy']
        Form.enemy_health = calculate_boss_health(boss)
        Form.resource = 1
        character = Character.objects.get(pk=self.kwargs['pk'])
        Form.character = character
        Form.character_health = calculate_player_health(character)
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class CharacterCreate(CreateView):
    model = Character
    form_class = CharacterCreate

    def form_valid(self, form):
        charactercreate = form.save(commit=False)
        charactercreate.user = self.request.user
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(CharacterCreate, self).get_context_data(**kwargs)
        context['types'] = Class.objects.all()
        return context

    def get_success_url(self):
        return reverse('character:detail', kwargs={'pk': self.object.pk})


def CharacterImage(request, pk):

    character =Character.objects.get(id=pk)
    media = "game/media/items/"
    background = Image.open("game/static/img/character-type/" + character.for_class.name + ".png")
    background = ImageOps.expand(background,border=80)

    equipped_items = ItemAcquired.objects.filter(character=pk, equipped_to__isnull=False)


    item_mapping = {
        'Head': (200, 27),
        'Left Hand': (55, 27),
    }

    hat = Image.open(media + "hat_nxY7RAW.png")
    background.paste(hat, (200, 27), hat)

    sword = Image.open(media + "sword-mounted_l9Rz3r8.png")
    background.paste(sword, (55, 27), sword)

    for i in equipped_items:
        item_image = Image.open("game" + i.item.image.url)
        background.paste(item_image, item_mapping[str(i.equipped_to)], item_image)

    response = HttpResponse(content_type="image/png")
    background.save(response, "PNG")


    return response

game/apps/items/views.py
from rest_framework import viewsets
from .serializers import ItemAcquiredSerializer, ItemSerializer
from .models import Item, ItemAcquired
from django.http import HttpResponse
from rest_framework.permissions import IsAuthenticated


class ItemAcquiredViewSet(viewsets.ModelViewSet):
    serializer_class = ItemAcquiredSerializer
    queryset = ItemAcquired.objects.all()
    permission_classes = (IsAuthenticated,)

    def get_queryset(self):
        user = self.request.user
        return ItemAcquired.objects.filter(character__user=user)

game/apps/matches/views.py
from django.views.generic import CreateView, DetailView, ListView
from django.views.generic.edit import ModelFormMixin
from .models import Match, Attack
from game.apps.characters.models import Character
from game.apps.enemies.models import Enemy
from .forms import CreateMatch, AttackForm
from game.apps.spells.models import Spell
from django.utils.timezone import now
from django.shortcuts import get_object_or_404
from django.core.urlresolvers import reverse
from .helpers import calculate_player_damage, calculate_boss_damage, calculate_player_health,  calculate_boss_health, calculate_xp


class CreateMatch(CreateView):
    model = Match
    form_class = CreateMatch

    def get_context_data(self, **kwargs):
        context = super(CreateMatch, self).get_context_data(**kwargs)
        context['characters'] = Character.objects.filter(user=self.request.user)
        context['enemys'] = Enemy.objects.all()
        return context

    def form_valid(self, form):
        Form = form.save(commit=False)
        boss = form.cleaned_data['enemy']
        Form.enemy_health = calculate_boss_health(boss)
        Form.resource = 1
        character = form.cleaned_data['character']
        Form.character_health = calculate_player_health(character)
        self.object = form.save()
        return super(ModelFormMixin, self).form_valid(form)


class MatchDetail(DetailView):
    model = Match

    def get_context_data(self, **kwargs):
        context = super(MatchDetail, self).get_context_data(**kwargs)

        context['spells'] = Spell.objects.filter(
            for_class=self.object.character.for_class,
            level_required__lte=context['match'].character.level_data()['current_level'],
        )

        match = get_object_or_404(
            Match,
            pk=self.kwargs.get('pk'),
            character__user=self.request.user,
        )

        if self.object.enemy_health == 0:
            context['condition'] = "win"
        else:
            if self.object.character_health == 0:
                context['condition'] = "loose"
            else:
                pass

        context['match'] = match

        cooldown = False

        for spell in context['spells']:
            attack_history_list = Attack.objects.filter(match=122).order_by('-time')[:spell.turn_cooldown]
            print attack_history_list
            for attack_history in attack_history_list:
                if attack_history.spell == attack_history_list:
                    cooldown = True
                    print cooldown
                    print attack_history.spell
                    context['cooldown'] = cooldown
                    break
                else:
                    cooldown = False
                    print cooldown
                    print attack_history.spell
                    context['cooldown'] = cooldown
        return context


class MatchList(ListView):
    model = Match


class AttackForm(CreateView):
    model = Attack
    form_class = AttackForm

    def get_context_data(self, **kwargs):
        context = super(AttackForm, self).get_context_data(**kwargs)
        match = get_object_or_404(
            Match,
            pk=self.kwargs.get('pk'),
            character__user=self.request.user
        )
        context['match'] = match
        return context

    def form_valid(self, form):
        spell = form.cleaned_data['spell']
        attackform = form.save(commit=False)
        match = Match.objects.get(id=self.kwargs['pk'])
        boss_spell = Spell.objects.filter(level_required__lte=match.enemy.level).order_by('?')[0]
        character_level = match.character.level_data()['current_level']
        attackform.enemy_return_spell = boss_spell
        character = match
        attackform.selected_spell = spell
        cooldown = False
        attack_history_list = Attack.objects.filter(match=match).order_by('-time')[:spell.turn_cooldown]
        player_damage = calculate_player_damage(character, spell)
        boss_damage = calculate_boss_damage(boss_spell, match)

        for attack_history in attack_history_list:
            if attack_history.spell == spell:
                cooldown = True
                break
            else:
                cooldown = False

        if spell.level_required <= character_level and spell.for_class == match.character.for_class and cooldown == False:

            if match.finished is False:
                if match.enemy_health <= player_damage:
                    match.enemy_health = 0
                    match.character.xp += calculate_xp(match)
                    match.finished = True
                else:
                    if match.character_health <= boss_damage:
                        match.character_health = 0
                        match.finished = True
                    else:
                        match.enemy_health -= player_damage
                        match.character_health -= boss_damage

            else:
                return super(ModelFormMixin, self).form_valid(form)

            attackform.damage_dealt = player_damage
            attackform.damage_taken = boss_damage

            attackform.match = match
            attackform.time = now()
            match.save()
            match.character.save()
            self.object = attackform.save()

            return super(ModelFormMixin, self).form_valid(form)
        else:
            return super(ModelFormMixin, self).form_valid(form)

    def get_success_url(self):
        return reverse('match:detail', kwargs={'pk': self.kwargs['pk']})

game/apps/messaging/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Message


class MessageList(ListView):
	model = Message

game/views.py
from django.views.generic import ListView
from game.apps.characters.models import Character

class Homepage(ListView):
    model = Character
    template_name = 'site/homepage.html'

    def get_context_data(self, **kwargs):
        context = super(Homepage, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            context['characters'] = Character.objects.filter(user=self.request.user)
        else:
            pass
        return context

game/templates/characters/character_detail.html
{% extends "base.html" %}
{% block content %}
  <style>
      .cd-character-items { 
          background-image: url('/static/img/character-type/{{ character.for_class}}.png');
      }
  </style>
  {% with level_data=character.level_data %}
    <div class="row">
      <div class="large-12 columns">
        <div class="cd-xp-bar" data-width="{{ level_data.xp_percentage }}"></div>
        <div class="cd-main">
          <h2>{{ character.name }} <small>Level {{ level_data.current_level }} {{ character.for_class }}</small></h2>
          <div class="large-5 columns">
            <ul class="cd-character-items">
                {% include 'characters/character_structure.html' %}
            </ul>
          </div>
          <div class="large-7 columns">
            <ul class="tabs" data-tabs id="example-tabs">
              <li class="tabs-title is-active"><a href="#panel1" aria-selected="true">Inventory</a></li>
              <li class="tabs-title"><a href="#panel2">Spells</a></li>
              <li class="tabs-title"><a href="#panel3">Statistics</a></li>
            </ul>
            <div class="tabs-content" data-tabs-content="example-tabs">
              <div class="tabs-panel is-active" id="panel1">
                <div class="large-8 columns cd-no-padding">
                  {% if character.itemacquired_set.all %}
                  <ul class="cd-inventory-bag">
                      {% for item in character.itemacquired_set.all  %}
                      <li id="inv-{{ item.id }}"  {% if item.equipped_to %}class="cd-item-hide"{% endif %}>
                        <img src="{{ item.item.icon.url }}">
                      </li>
                      <div id="inv-{{ item.id }}-dropdown" class="cd-spell-hide">
                        <ul class="cd-spell-detail">
                          <li><img src="{{ item.item.icon.url }}"></li>
                          <li><h4>{{ item.item.name  }}</h4></li>
                          <li>Damage: {{ item.item.damage }}</li>
                          <li>Healing: {{ item.item.healing }}</li>
                          <li>Armor: {{ item.item.armor }}</li>
                        </ul>
                      </div>
                      {% endfor %}
                  </ul>
                  {% endif %}
                </div>
                <div class="large-4 columns cd-no-padding">
                  <div class="cd-spell-sidebar" id="inv-sidebar"></div>
                </div>
              </div>
              <div class="tabs-panel" id="panel2">
                <div class="large-8 columns cd-no-padding">
                  <ul class="cd-spells">
                    {% for item in spells %}
                      <li id="spell-{{ item.id }}"><img src="{{ item.spell.image.url }}"></li>
                      <div id="spell-{{ item.id }}-dropdown" class="cd-spell-hide">
                        <ul class="cd-spell-detail">
                          <li><img src="{{ item.spell.image.url }}"></li>
                          <li><h4>{{ item.spell.name }}</h4></li>
                          <li>Spell Damage: {{ item.spell.damage }}</li>
                          <li>Level Required: {{ item.spell.level_required }}</li>
                          <li>Turn Cooldown: {{ item.spell.turn_cooldown }}</li>
                        </ul>
                      </div>
                    {% endfor %}
                  </ul>
                </div>
                <div class="large-4 columns cd-no-padding">
                  <div class="cd-spell-sidebar" id="sidebar"></div>
                </div>
              </div>
              <div class="tabs-panel" id="panel3">
                <ul class="cd-statistics">
                  {% for match in character.match_set.all  %}
                    <li>
                      <a href="/match/{{ match.id }}/">
                        {{ match.character }} vs {{ match.enemy }}
                        {% if match.enemy_health == 0 %}
                          <span class="success label">Won</span>
                        {% elif match.character_health == 0 %}
                          <span class="alert label">Lost</span>
                        {% else %}
                          <span class="warning label">Unfinished</span>
                        {% endif %}
                      </a>
                    </li>
                  {% endfor %}
                </ul>
              </div>
            </div>
            <a href="{{ character.get_absolute_url }}/create" class="button">Start Match</a>
          </div>
        </div>
      </div>
    </div>
  {% endwith %}
{% endblock %}

{% block js %}
  <script src="/static/js/apps/characters.js"></script>
  <script>
  $(function() {
      $('.cd-xp-bar').width($('.cd-xp-bar').data('width') + '%');
  });
  </script>
{% endblock %}

game/templates/characters/character_form.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="large-12 columns">
        <h2 class="cc-heading">Create a character</h2>
    </div>
    <div class="large-12 columns left">
        <form action="" method="post">
            {% csrf_token %}
            <input id="cc-name" maxlength="150" name="name" placeholder="Name..." type="text" required autofocus>
            {{ form.errors.name }}
            {% for type in types %}
                <input type="radio" name="for_class" class="cc-type" value="{{ type.id }}" id="{{ type.name }}">
                <label for="{{ type.name }}" class="cc-type"><img src="/static/img/character-type/{{ type.name }}.png">{{ type.name }}</label>
            {% endfor %}
            {{ form.errors.type }}
            <hr>
            <input type="submit" value="Create" class="button darkblack">
        </form>
    </div>
</div>



{% endblock %}

game/templates/characters/character_list.html
{% extends "base.html" %}
{% block content %}
    <div class="row">
        <div class="large-12 columns">
            <h1>Leaderboard</h1>
            <hr>
            <p>Here are the top 100 characters!</p>
            <ol>
                {% for character in character_list %}
                    <li><a href="/character/{{ character.id }}">{{ character.name }}</a></li>
                {% endfor %}
            </ol>
        </div>
    </dov>
{% endblock content %}

game/templates/characters/character_structure.html
{% if character.for_class.name == 'Wizard' %}
	<li style="left: 39%;top: 4%;width: 108px;min-height: 108px;" id="{{ head.id }}"><img src="{{ item_head }}" id="{{ head_id }}"></li>
	<li style="left: 7%;top: 3%;width: 68px;min-height: 232px;" id="{{ left_hand.id }}"><img src="{{ item_left_hand }}" id="{{ left_hand_id }}"></li>
	<li style="left: 65%;top: 34%;width: 107px;min-height: 162px;" id="{{ right_hand.id }}"><img src="{{ item_right_hand }}" id="{{ right_hand_id }}"></li>
	<li style="left: 30%;top: 66%;width: 158px;min-height: 72px;"><img src="{{ item_feet }}"></li>
{% endif %}

game/templates/characters/item_list.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="large-3 columns">
        <form action="">
        <input type="text" name="q" placeholder="Search for a item...">
        </form>
        <ul class="shop-classes">
            <li><a href="/">Example Class</a></li>
        </ul>
    </div>
    <div class="large-9 columns" data-equalizer>
        <h1>Shop </h1>
        <hr>


        <div id="effect-1" class="effects clearfix">
        {% for item in item_list %}
        <div class="large-4 columns left" data-equalizer-watch>
            <div class="img">
                <small class="price">Price: ${{ item.worth }}</small>
                <img src="http://piq.codeus.net/static/media/userpics/piq_47498_400x400.png" alt="">
                <hr>
                <h3>{{ item.name }}</h3>
                <div class="overlay">
                <a href="#" class="expand">+</a>

                <a class="close-overlay hidden">x</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}
{% block js %}
<script type="text/javascript">
$(document).ready(function(){
    if (Modernizr.touch) {
        // show the close overlay button
        $(".close-overlay").removeClass("hidden");
        // handle the adding of hover class when clicked
        $(".img").click(function(e){
            if (!$(this).hasClass("hover")) {
                $(this).addClass("hover");
            }
        });
        // handle the closing of the overlay
        $(".close-overlay").click(function(e){
            e.preventDefault();
            e.stopPropagation();
            if ($(this).closest(".img").hasClass("hover")) {
                $(this).closest(".img").removeClass("hover");
            }
        });
    } else {
        // handle the mouseenter functionality
        $(".img").mouseenter(function(){
            $(this).addClass("hover");
        })
        // handle the mouseleave functionality
        .mouseleave(function(){
            $(this).removeClass("hover");
        });
    }
});
</script>
{% endblock js %}